<!DOCTYPE html>
<html>
<head>
<link href="css/style.css" media="all" rel="stylesheet" type="text/css">
</head>
<body>
    <div id="main">
        
        <div class="container-center">
        
            <div class="header-top">
                
                <ul class="user-link">
                    <li>
                        <a class="account" href="">
                    <span>Account</span>
                        </a>
                    </li>
                    <li>
                        <a class="sign-out" href="index.php?session=delete">
                    <span>Sign Out</span>
                    </a>
                    </li>
                </ul>

            </div>

        </div>