<footer id="footer">
		<div class="footer-top">
				<div class="footer-nav">
					 <ul>
                        <li><a  class="active" href="index.php">Головна</a></li>
                        <li><a  href="">Мої результати</a></li>
                        <li><a  href="">Мої активні партії</a></li>

                    </ul>
					<ul>
                        <li><a  href="">Гра</a></li>
                        <li><a  href="">Всі результати</a></li>
					</ul>
					<ul>
						<li>
							<span class="has-ico">Chess</span>
						</li>
						<li>
							Uzhhorod
						</li>
					</ul>
				</div>		
		</div>
		<div class="footer-bottom">
				<div class="copy">&copy; 2014 Offdark. All Rights Reserved =)</div>
		</div>
	</footer>
</body>
</html>
