<!DOCTYPE html>
<html>
<head>
<link href="css/style.css" media="all" rel="stylesheet" type="text/css">
</head>
<body>
    <div id="main">
        
        <div class="container-center">
        
            <div class="header-top">
                
                <ul class="user-link">
                    <li>
                        <a class="sign-up" href="add.php">
                    <span>Sign Up</span>
                        </a>
                    </li>
                    <li>
                        <a class="sign-in" href="login.php">
                    <span>Sign In</span>
                    </a>
                    </li>
                </ul>

            </div>

        </div>