<div class="container-content">

    content


    <form action="add.php" method="POST" class="form" >
        <fieldset>

            <label>Login <span class="mark-red">*</span>
                <input id="Username" class="input" type="text" name="login" required /><br />
            </label>

            <label>E-mail <span class="mark-red">*</span>
                <input id="Password" class="input" type="email" name="email" required /><br />
            </label>

            <label>Name <span class="mark-red">*</span>
                <input id="Username" class="input" type="text" name="realName" required /><br />
            </label>

            <label>Password <span class="mark-red">*</span>
                <input id="Password" class="input" type="password" name="password" required /><br />
            </label>

            <label>Repeat Password <span class="mark-red">*</span>
                <input id="Password" class="input" type="password" name="re_password" required /><br />
            </label>

            <input type="submit" name="singUp" class="btn-form" value="Sign Up" />

        </fieldset>
    </form>

</div>